import cds from '@sap/cds/eslint.config.mjs'
import globals from 'globals'
import tseslint from 'typescript-eslint'

export default [
    {
        ignores: [
            '**/node_modules/**',
            '**/coverage/**',
            // GENERATED by `npm run build:slim`; the originals are linted at
            // their real location under src/ and srv/.
            'packages/nightgate-tx/**',
            // Local-only measurement probes and one-off scripts (gitignored, never packed).
            'scratch/**',
            // Private context and helpers (gitignored, never published).
            'local_docs/**',
            '**/gen/**',
            '@cds-models/**',
            'src/**/*.js',
            'src/**/*.d.ts',
            'src/**/*.js.map',
            'src/**/*.d.ts.map',
            'srv/**/*.js',
            'srv/**/*.d.ts',
            'srv/**/*.js.map',
            'srv/**/*.d.ts.map',
            'test/**/*.js',
            'test/**/*.d.ts',
            // scripts/ are runners and probes, except the published bins
            // (file patterns, not a directory pattern: a negation cannot
            // un-ignore a file below an ignored directory).
            'scripts/**/*.{js,mjs,cjs,ts}',
            '!scripts/apply-schema-delta.mjs',
            '!scripts/fetch-contract-keys.mjs',
            '!scripts/migrate-sqlite-to-postgres.mjs'
        ]
    },
    ...cds.recommended,
    {
        // The published bins are CLIs; their output IS the console.
        files: ['scripts/*.mjs'],
        rules: { 'no-console': 'off' }
    },
    {
        // The src/browser building blocks run in the browser (Lace connector),
        // not Node, so they use browser globals (WebSocket, TextEncoder, crypto,
        // fetch, localStorage, ...).
        files: ['src/browser/**/*.mjs'],
        languageOptions: {
            globals: { ...globals.browser }
        }
    },
    {
        files: ['**/*.ts'],
        languageOptions: { parser: tseslint.parser },
        plugins: { '@typescript-eslint': tseslint.plugin },
        rules: {
            // The compiler checks names and overloads; the base rules misread types.
            'no-undef': 'off',
            'no-redeclare': 'off',
            'no-unused-vars': 'off',
            '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' }],
            '@typescript-eslint/no-explicit-any': 'warn'
        }
    },
    {
        // SDK objects are duck-typed (real types would pull in the ESM-only SDK type graphs); test doubles too.
        files: ['srv/midnight/**/*.ts', 'test/**/*.ts'],
        rules: { '@typescript-eslint/no-explicit-any': 'off' }
    }
]
