/**
 * Fee sponsoring: a sponsor wallet pays the dust fee for a tx another party built.
 * Each dust note is generated by one NIGHT UTXO, called its backing here.
 * Parallel sponsoring reserves one backing per tx so the spends never collide.
 */

// Must stay the first import. The worker modules import each other in a cycle,
// and config is read at load time.
import { configNumber, configMs } from '../../utils/config';
import { throwIfRpcCancelled } from './cancellation';
import { callSegments } from '../batch-segment-order';
import { SponsorRefusalError } from '../submit-error-classification';
import { formatErr } from '../../utils/format-error';
import { getSharedKeyMaterialProvider } from '../wasm-proof-provider';
import { type MerkleProofBundle } from '../../submission/contract-witnesses';
import { type MessagePort } from 'node:worker_threads';
import { FacadeEntry, ensureNetworkId, facades, loadContractsSdk, loadDustCoreWallet, loadProvingSdk, loadSdk, log, resolveProvingMode, loadLedger } from './context';
import { artifactAssetPath } from './artifacts';
import { buildWorkerContractProviders, getOrCompileContract, withFindContractQueryCache } from './contracts';
import { createPrivateStateProxy } from './private-state';
import { BALANCE_SYNC_TIMEOUT_MS, getIndexerTip, waitForGenuineSync, withSessionLocks } from './facades';
import { announceSubmitIntent, buildBuildOnlyWalletProvider, captureDustSnapshot, revertRecipeBestEffort, submitOnDedicatedClient, submitWithDustGuard } from './submit';
import { HEX64_RE } from '../../utils/hex-patterns';

/** Reads a caller tx from base64, bound or not yet bound. */
export async function deserializeFinalizedTx(b64: string): Promise<{ tx: any; bytes: Uint8Array }> {
    const bytes = new Uint8Array(Buffer.from(b64, 'base64'));
    const ledger: any = await loadLedger();
    const attempts: Array<[string, string, string]> = [
        ['signature', 'proof', 'binding'],
        ['signature', 'proof', 'pre-binding']
    ];
    const errs: string[] = [];
    for (const [s, p, b] of attempts) {
        try { const tx = ledger.Transaction.deserialize(s, p, b, bytes); if (tx) return { tx, bytes }; }
        catch (e) { errs.push(`(${s},${p},${b}): ${formatErr(e).slice(0, 60)}`); }
    }
    throw new Error(`could not deserialize finalized tx (${bytes.length}B); tried ${errs.join(' | ')}`);
}

export function inspectTxCalls(tx: any): Array<{ address: string; entryPoint: string }> {
    const out: Array<{ address: string; entryPoint: string }> = [];
    try {
        const intents: Map<number, any> | undefined = tx?.intents;
        if (!intents || typeof intents.entries !== 'function') return out;
        for (const [, intent] of Array.from(intents.entries())) {
            for (const action of (intent?.actions ?? [])) {
                const ep = action?.entryPoint;
                const name = typeof ep === 'string' ? ep : (ep instanceof Uint8Array ? new TextDecoder().decode(ep) : '');
                if (name) out.push({ address: String(action?.address ?? ''), entryPoint: name });
            }
        }
    } catch { /* best-effort inspection */ }
    return out;
}

/** True when an offer or action list is not empty. */
export function offerNonEmpty(offer: any): boolean {
    if (!offer) return false;
    let sawKnownKey = false;
    for (const key of ['inputs', 'outputs', 'transient', 'spends', 'registrations', 'deltas']) {
        const v = offer[key];
        if (v === undefined) continue;
        sawKnownKey = true;
        if (v === null) continue;
        if (Array.isArray(v)) { if (v.length > 0) return true; continue; }
        if (typeof v?.size === 'number') { if (v.size > 0) return true; continue; }
        if (typeof v?.length === 'number') { if (v.length > 0) return true; continue; }
        return true;
    }
    // Treat an unreadable shape as not empty, so it gets refused.
    return !sawKnownKey;
}

export function normalizeTokenType(t: unknown): string {
    return String(t ?? '').trim().toLowerCase().replace(/^0x/, '');
}

/** Amount minted by the tx's calls, per raw token type. The offer check uses it up as it goes. */
export type MintBudget = Map<string, bigint>;

/**
 * What the calls on sponsorable contracts mint. Read from the call results, which the proof covers.
 * The token type is derived from the domain separator and the contract address.
 */
export function declaredMints(
    tx: any,
    contractSponsorable: (address: string) => boolean,
    deriveTokenType: (domainSeparatorHex: string, contractAddress: string) => string
): MintBudget {
    const budget: MintBudget = new Map();
    const intents: Map<number, any> | undefined = tx?.intents;
    if (!intents || typeof intents.values !== 'function') return budget;
    for (const intent of Array.from(intents.values())) {
        for (const action of (intent?.actions ?? [])) {
            const address = String(action?.address ?? '');
            if (!address || !contractSponsorable(address)) continue;
            for (const transcript of [action?.guaranteedTranscript, action?.fallibleTranscript]) {
                const mints = transcript?.effects?.shieldedMints;
                if (!mints || typeof mints.entries !== 'function') continue;
                for (const [domainSeparator, amount] of Array.from(mints.entries() as Iterable<[unknown, unknown]>)) {
                    if (typeof amount !== 'bigint' || amount <= 0n) continue;
                    const type = normalizeTokenType(deriveTokenType(normalizeTokenType(domainSeparator), address));
                    if (!HEX64_RE.test(type)) continue;
                    budget.set(type, (budget.get(type) ?? 0n) + amount);
                }
            }
        }
    }
    return budget;
}

/**
 * Throws unless every token the offer moves is allowed or minted by a call in the same tx,
 * never NIGHT, and every contract coin belongs to a sponsorable contract.
 * An offer that nets to zero hides what it moves, so it is refused unless a contract coin
 * shows it is the call's own value, for example a burn.
 */
export function checkOfferTokens(offer: any, key: string, tokenTypes: string[], nightType: string | undefined, contractSponsorable: (address: string) => boolean, mints: MintBudget = new Map()): void {
    const deltas = offer?.deltas;
    const entries: Array<[unknown, unknown]> | null = typeof deltas?.entries === 'function'
        ? Array.from(deltas.entries() as Iterable<[unknown, unknown]>)
        : (Array.isArray(deltas) ? deltas as Array<[unknown, unknown]> : null);
    if (!entries) throw new SponsorRefusalError(`refusing to sponsor: ${key} exposes no deltas (token types not inspectable)`);
    if (entries.length === 0) {
        const contractCoin = ['inputs', 'outputs', 'transients', 'transient'].some((coll) =>
            Array.isArray(offer?.[coll]) && offer[coll].some((coin: any) => coin?.contractAddress !== undefined && coin?.contractAddress !== null));
        if (!contractCoin) {
            throw new SponsorRefusalError(`refusing to sponsor: ${key} nets to zero and carries no contract-owned coin (a shielded transfer alongside the call, not value the call moves)`);
        }
    }
    for (const [rawType, rawDelta] of entries) {
        const type = normalizeTokenType(rawType);
        if (nightType && type === nightType) throw new SponsorRefusalError(`refusing to sponsor: ${key} moves NIGHT`);
        if (tokenTypes.includes(type)) continue;
        const minted = mints.get(type);
        if (minted === undefined) throw new SponsorRefusalError(`refusing to sponsor: ${key} moves token type ${type.slice(0, 16)}…, not in allowedTokenTypes`);
        // Delta is inputs minus outputs, so a mint shows as a negative delta. It may not exceed the minted amount.
        const taken = typeof rawDelta === 'bigint' ? -rawDelta : null;
        if (taken === null || taken <= 0n) {
            throw new SponsorRefusalError(`refusing to sponsor: ${key} pays in token type ${type.slice(0, 16)}…, not in allowedTokenTypes (a mint in the same transaction covers only what it creates)`);
        }
        if (taken > minted) {
            throw new SponsorRefusalError(`refusing to sponsor: ${key} creates ${taken} of token type ${type.slice(0, 16)}…, the transaction's calls mint ${minted}`);
        }
        mints.set(type, minted - taken);
    }
    for (const coll of ['inputs', 'outputs', 'transients', 'transient']) {
        const list = offer?.[coll];
        if (!Array.isArray(list)) continue;
        for (const coin of list) {
            const owner = coin?.contractAddress;
            if (owner === undefined || owner === null) continue;
            const address = String(owner);
            if (!address || !contractSponsorable(address)) {
                throw new SponsorRefusalError(`refusing to sponsor: ${key} carries a coin owned by contract ${address.slice(0, 16)}…, which is not sponsorable here`);
            }
        }
    }
}

/** Stands for a sponsored swap in the returned call list. */
export const SWAP_ENTRY_POINT = '<swap>';

/** What a swap exchanges, from the maker's side. Amounts in atoms. */
export interface SwapTerms {
    gives: { tokenType: string; amount: string };
    wants: { tokenType: string; amount: string };
}

const sizeOf = (v: any): number | null =>
    Array.isArray(v) ? v.length : typeof v?.size === 'number' ? v.size : typeof v?.length === 'number' ? v.length : null;

/**
 * A swap half is a single offer that gives one token type and wants another.
 * Its terms come from the offer's two deltas, because the coins do not show their type.
 */
function swapHalfTerms(half: any, label: string, tokenTypes: string[] | null, nightType: string | undefined, maxInputs: number, prefix = 'refusing to sponsor'): { give: [string, bigint]; want: [string, bigint] } {
    const refuse = (why: string): never => { throw new SponsorRefusalError(`${prefix}: the ${label} ${why}`); };
    const intents = half?.intents;
    if (intents !== undefined && intents !== null && sizeOf(intents) !== 0) refuse('carries an intent (a contract call, unshielded value or dust actions)');
    const fallible = half?.fallibleOffer;
    if (fallible !== undefined && fallible !== null && sizeOf(fallible) !== 0) refuse('carries a fallible offer');
    const offer = half?.guaranteedOffer;
    if (!offer || !Array.isArray(offer.inputs) || !Array.isArray(offer.outputs)) return refuse('carries no readable guaranteed offer');
    if (sizeOf(offer.transients ?? []) !== 0) refuse('carries a transient coin');
    if ([...offer.inputs, ...offer.outputs].some((coin: any) => coin?.contractAddress !== undefined && coin?.contractAddress !== null)) {
        refuse('carries a contract-owned coin');
    }
    if (offer.inputs.length < 1 || offer.inputs.length > maxInputs) refuse(`carries ${offer.inputs.length} inputs; 1 to ${maxInputs} are sponsored (NIGHTGATE_SPONSOR_SWAP_MAX_INPUTS)`);
    if (offer.outputs.length < 1 || offer.outputs.length > 2) refuse(`carries ${offer.outputs.length} outputs; a half has the coin it wants and at most its change`);
    const deltas = offer.deltas;
    const entries: Array<[unknown, unknown]> | null = typeof deltas?.entries === 'function' ? Array.from(deltas.entries() as Iterable<[unknown, unknown]>) : null;
    if (!entries) return refuse('exposes no deltas (terms not readable)');
    const typed = entries.map(([t, v]) => [normalizeTokenType(t), v] as [string, unknown]);
    if (typed.some(([, v]) => typeof v !== 'bigint' || v === 0n)) refuse('exposes a delta that is not a non-zero amount');
    const gives = typed.filter(([, v]) => (v as bigint) > 0n) as Array<[string, bigint]>;
    const wants = typed.filter(([, v]) => (v as bigint) < 0n) as Array<[string, bigint]>;
    if (gives.length !== 1 || wants.length !== 1) refuse(`gives ${gives.length} token type(s) and wants ${wants.length}; a half gives one and wants one`);
    const give = gives[0];
    const want: [string, bigint] = [wants[0][0], -wants[0][1]];
    if (give[0] === want[0]) refuse('gives and wants the same token type');
    for (const [type] of [give, want]) {
        if (nightType && type === nightType) refuse('moves NIGHT');
        if (tokenTypes && !tokenTypes.includes(type)) refuse(`moves token type ${type.slice(0, 16)}…, not in allowedTokenTypes`);
    }
    return { give, want };
}

/** Nullifiers of a half's inputs. Once they show as spent on chain, the half can no longer be used. */
export function swapHalfNullifiers(half: any): string[] {
    const inputs: any[] = Array.isArray(half?.guaranteedOffer?.inputs) ? half.guaranteedOffer.inputs : [];
    return [...new Set(inputs.map((i: any) => normalizeTokenType(i?.nullifier)).filter((n: string) => HEX64_RE.test(n)))];
}

export interface SwapHalfDescription extends SwapTerms {
    bound: boolean;
    inputs: number;
    nullifiers: string[];
}

/** Reads one half's terms. Checks its shape like a sponsored half, but without the token allow list. */
export async function describeSwapHalf(args: { halfB64: string }): Promise<SwapHalfDescription> {
    const half = await deserializeSwapHalf(args.halfB64, 'half');
    const ledger: any = await loadLedger();
    const nightType = normalizeTokenType(ledger.nativeToken().raw);
    const t = swapHalfTerms(half.tx, 'half', null, nightType, configNumber('NIGHTGATE_SPONSOR_SWAP_MAX_INPUTS'), 'not a swap half');
    return {
        gives: { tokenType: t.give[0], amount: t.give[1].toString() },
        wants: { tokenType: t.want[0], amount: t.want[1].toString() },
        bound: half.bound,
        inputs: half.tx.guaranteedOffer.inputs.length,
        nullifiers: swapHalfNullifiers(half.tx)
    };
}

/** Throws unless the two halves are exact mirror images. Returns the terms. */
export function checkSwapHalves(
    maker: any, taker: any,
    options: { allowedTokenTypes?: string[]; nightTokenType?: string; maxInputs?: number } = {}
): SwapTerms {
    const tokenTypes = (options.allowedTokenTypes ?? []).map(normalizeTokenType);
    if (tokenTypes.length === 0) throw new SponsorRefusalError('refusing to sponsor: a swap needs its token types in allowedTokenTypes, and none is listed');
    const nightType = options.nightTokenType ? normalizeTokenType(options.nightTokenType) : undefined;
    const maxInputs = Number.isInteger(options.maxInputs) && (options.maxInputs as number) >= 1 ? (options.maxInputs as number) : 4;
    const m = swapHalfTerms(maker, 'maker half', tokenTypes, nightType, maxInputs);
    const t = swapHalfTerms(taker, 'taker half', tokenTypes, nightType, maxInputs);
    if (m.give[0] !== t.want[0] || m.give[1] !== t.want[1] || m.want[0] !== t.give[0] || m.want[1] !== t.give[1]) {
        throw new SponsorRefusalError(
            `refusing to sponsor: the halves do not mirror each other (maker gives ${m.give[1]} of ${m.give[0].slice(0, 16)}… for ${m.want[1]} of ${m.want[0].slice(0, 16)}…, ` +
            `taker gives ${t.give[1]} of ${t.give[0].slice(0, 16)}… for ${t.want[1]} of ${t.want[0].slice(0, 16)}…)`);
    }
    return {
        gives: { tokenType: m.give[0], amount: m.give[1].toString() },
        wants: { tokenType: m.want[0], amount: m.want[1].toString() }
    };
}

/** Throws unless the merged halves balance, so the sponsor adds only the fee, never value. */
export function assertSwapBalanced(merged: any, byteLength: number): void {
    const maxBytes = configNumber('NIGHTGATE_SPONSOR_MAX_TX_BYTES');
    if (byteLength > maxBytes) {
        throw new SponsorRefusalError(`refusing to sponsor: the merged swap is ${byteLength}B, over the ${maxBytes}B budget (NIGHTGATE_SPONSOR_MAX_TX_BYTES)`);
    }
    if (merged?.intents !== undefined && merged?.intents !== null && sizeOf(merged.intents) !== 0) {
        throw new SponsorRefusalError('refusing to sponsor: the merged swap carries an intent');
    }
    const deltas = merged?.guaranteedOffer?.deltas;
    if (sizeOf(deltas) !== 0) throw new SponsorRefusalError('refusing to sponsor: the merged swap does not net to zero');
    let imbalances: Array<[unknown, unknown]>;
    try { imbalances = Array.from(merged.imbalances(0).entries() as Iterable<[unknown, unknown]>); }
    catch (e) { throw new SponsorRefusalError(`refusing to sponsor: the merged swap's balance is not readable (${formatErr(e).slice(0, 80)})`); }
    if (imbalances.some(([, v]) => v !== 0n)) throw new SponsorRefusalError('refusing to sponsor: the merged swap does not balance');
}

/** A swap half must be proven. It may be bound, as in an offer file, or not yet bound. */
async function deserializeSwapHalf(b64: string, label: string): Promise<{ tx: any; bound: boolean }> {
    const bytes = new Uint8Array(Buffer.from(String(b64 ?? ''), 'base64'));
    if (bytes.length === 0) throw new SponsorRefusalError(`refusing to sponsor: the ${label} is empty`);
    const ledger: any = await loadLedger();
    const errors: string[] = [];
    for (const binding of ['binding', 'pre-binding']) {
        try {
            return { tx: ledger.Transaction.deserialize('signature', 'proof', binding, bytes), bound: binding === 'binding' };
        } catch (e) {
            errors.push(`${binding}: ${formatErr(e).slice(0, 60)}`);
        }
    }
    throw new SponsorRefusalError(`refusing to sponsor: the ${label} is not a proven transaction (${bytes.length}B; ${errors.join(' | ')})`);
}

/**
 * Merges two checked halves into one tx. A bound and an unbound tx cannot be merged,
 * so if one half is bound the other is bound first.
 */
export function mergeSwapHalves(maker: { tx: any; bound: boolean }, taker: { tx: any; bound: boolean }): { tx: any; bound: boolean } {
    const bound = maker.bound || taker.bound;
    try {
        const m = bound && !maker.bound ? maker.tx.bind() : maker.tx;
        const t = bound && !taker.bound ? taker.tx.bind() : taker.tx;
        return { tx: m.merge(t), bound };
    } catch (e) {
        throw new SponsorRefusalError(`refusing to sponsor: the halves do not merge: ${formatErr(e).slice(0, 120)}`);
    }
}

function mintedTypesOf(tx: any, allowContractMints: boolean | undefined, ledger: any): string[] {
    if (allowContractMints !== true) return [];
    return Array.from(declaredMints(tx, () => true, tokenTypeDeriver(ledger)).keys());
}

export function tokenTypeDeriver(ledger: any): (domainSeparatorHex: string, contractAddress: string) => string {
    return (domainSeparatorHex, contractAddress) =>
        String(ledger.rawTokenType(new Uint8Array(Buffer.from(domainSeparatorHex, 'hex')), contractAddress));
}

/** Stands for a sponsored deploy in the returned call list. */
export const DEPLOY_ENTRY_POINT = '<deploy>';

/**
 * Checks what a tx contains before the sponsor pays for it.
 * An allowed call could hide a deploy, transfers or dust actions in the same tx.
 * Anything that cannot be read is refused.
 */
export function checkSponsorableShape(
    tx: any,
    byteLength: number,
    allowedContracts?: string[],
    allowedCircuits?: string[],
    options: {
        allowDeploy?: boolean; maxDeploys?: number; ownContracts?: string[]; allowedTokenTypes?: string[]; nightTokenType?: string;
        /** Set both to also pay for tokens the calls mint. */
        allowContractMints?: boolean; deriveTokenType?: (domainSeparatorHex: string, contractAddress: string) => string;
    } = {}
): Array<{ address: string; entryPoint: string }> {
    const tokenTypes = (options.allowedTokenTypes ?? []).map(normalizeTokenType);
    const nightType = options.nightTokenType ? normalizeTokenType(options.nightTokenType) : undefined;
    const contractSponsorable = (address: string): boolean =>
        !allowedContracts?.length || allowedContracts.includes(address)
        || (Array.isArray(options.ownContracts) && options.ownContracts.includes(address));
    const maxDeploysPerTx = Number.isInteger(options.maxDeploys) && (options.maxDeploys as number) >= 0 ? (options.maxDeploys as number) : 1;
    let deployCount = 0;
    const maxBytes = configNumber('NIGHTGATE_SPONSOR_MAX_TX_BYTES');
    if (byteLength > maxBytes) {
        throw new SponsorRefusalError(`refusing to sponsor: transaction is ${byteLength}B, over the ${maxBytes}B budget (NIGHTGATE_SPONSOR_MAX_TX_BYTES)`);
    }

    const intents: Map<number, any> | undefined = tx?.intents;
    if (!intents || typeof intents.entries !== 'function') {
        throw new SponsorRefusalError('refusing to sponsor: transaction structure is not inspectable (no intents)');
    }
    const mints: MintBudget = options.allowContractMints === true && options.deriveTokenType
        ? declaredMints(tx, contractSponsorable, options.deriveTokenType)
        : new Map();
    for (const key of ['guaranteedOffer', 'fallibleOffer', 'guaranteedCoins', 'fallibleCoins']) {
        const offer = (tx as any)[key];
        if (offer === undefined || offer === null) continue;
        const parts: unknown[] = typeof offer?.entries === 'function' && !('inputs' in offer)
            ? Array.from(offer.entries() as Iterable<[unknown, unknown]>).map(([, sub]) => sub)
            : [offer];
        for (const part of parts) {
            if (!offerNonEmpty(part)) continue;
            if (tokenTypes.length === 0 && mints.size === 0) throw new SponsorRefusalError(`refusing to sponsor: transaction carries a ${key} (shielded value transfer)`);
            checkOfferTokens(part, key, tokenTypes, nightType, contractSponsorable, mints);
        }
    }

    const calls: Array<{ address: string; entryPoint: string }> = [];
    for (const [, intent] of Array.from(intents.entries())) {
        // The caller pays no fee, so it has no reason to carry dust actions.
        for (const key of ['guaranteedUnshieldedOffer', 'fallibleUnshieldedOffer', 'dustActions']) {
            if (offerNonEmpty(intent?.[key])) {
                throw new SponsorRefusalError(`refusing to sponsor: transaction carries ${key} alongside its contract calls`);
            }
        }
        for (const action of (intent?.actions ?? [])) {
            const ep = action?.entryPoint;
            const name = typeof ep === 'string' ? ep : (ep instanceof Uint8Array ? new TextDecoder().decode(ep) : '');
            if (!name) {
                const kind = action?.constructor?.name || typeof action;
                // Maintenance updates change who controls a contract, so they are never sponsored.
                // Detected by shape too, not only by class name.
                const isMaintenance = kind === 'MaintenanceUpdate' || action?.updates !== undefined;
                if (isMaintenance) {
                    throw new SponsorRefusalError('refusing to sponsor: transaction carries a contract maintenance update (never sponsorable)');
                }
                const isDeploy = kind === 'ContractDeploy' || (action?.initialState !== undefined && action?.address !== undefined);
                if (isDeploy && options.allowDeploy === true) {
                    const address = String(action?.address ?? '');
                    if (!address) throw new SponsorRefusalError('refusing to sponsor: deploy action carries no contract address');
                    deployCount++;
                    if (deployCount > maxDeploysPerTx) {
                        throw new SponsorRefusalError(`refusing to sponsor: transaction carries ${deployCount}+ contract deploys; at most ${maxDeploysPerTx} per sponsored transaction`);
                    }
                    // Deploys carry verifier keys, so they have their own size limit.
                    const maxDeployBytes = configNumber('NIGHTGATE_SPONSOR_MAX_DEPLOY_BYTES');
                    if (byteLength > maxDeployBytes) {
                        throw new SponsorRefusalError(`refusing to sponsor: deploy transaction is ${byteLength}B, over the ${maxDeployBytes}B deploy budget (NIGHTGATE_SPONSOR_MAX_DEPLOY_BYTES)`);
                    }
                    calls.push({ address, entryPoint: DEPLOY_ENTRY_POINT });
                    continue;
                }
                throw new SponsorRefusalError(`refusing to sponsor: transaction carries a non-call action (${kind})${isDeploy ? '; deploys need allowDeploy on the grant and NIGHTGATE_SPONSOR_ALLOW_DEPLOY on the server' : ''}`);
            }
            const address = String(action?.address ?? '');
            if (allowedContracts?.length && !allowedContracts.includes(address)) {
                throw new SponsorRefusalError(`refusing to sponsor: contract ${address.slice(0, 16)} is not in the allow-list`);
            }
            const own = Array.isArray(options.ownContracts) && options.ownContracts.includes(address);
            if (!own && allowedCircuits?.length && !allowedCircuits.includes(name)) {
                throw new SponsorRefusalError(`refusing to sponsor: circuit '${name}' is not sponsorable`);
            }
            calls.push({ address, entryPoint: name });
        }
    }
    if (calls.length === 0) throw new SponsorRefusalError('refusing to sponsor: the transaction carries no contract call');
    return calls;
}

/** The current dust wallet state. */
export async function firstDustState(dust: any): Promise<any> {
    return await new Promise((resolve, reject) => {
        let done = false;
        const sub = dust.state?.subscribe?.({
            next: (v: any) => { if (!done) { done = true; setImmediate(() => sub?.unsubscribe?.()); resolve(v); } },
            error: (e: any) => { if (!done) { done = true; reject(e); } }
        });
        if (!sub) reject(new Error('facade.dust.state not observable'));
        setTimeout(() => { if (!done) { done = true; try { sub?.unsubscribe?.(); } catch { /* */ } reject(new Error('no dust emission in 10s')); } }, 10_000);
    });
}

/**
 * Reservations of backings. They expire, so a crashed call frees its reservation.
 * The token ensures a late caller cannot release a reservation someone else took over.
 */
export const noteLocks = new Map<string, { exp: number; token: number }>();
export let noteLeaseSeq = 0;

/**
 * Reservations are per backing, not per note. Notes of one backing conflict when spent
 * at the same time, which the node rejects with 1010/196.
 */
export function backingKey(sessionId: string, note: any): string {
    return `${sessionId}|${note?.token?.backingNight ?? '?'}`;
}
/** Dust a note holds. 0 when unreadable. */
export function noteSpecks(note: any): bigint {
    try { return BigInt(note?.generatedNow ?? 0); } catch { return 0n; }
}

/**
 * Reserves the free backing with the most dust, which spreads the load.
 * `notes` must be valued at the block time of the spend. Dust grows over time,
 * so reading it at the current clock time shows too much.
 */
export function tryLockBacking(sessionId: string, notes: any[], needSpecks: bigint, ttlMs: number, skipBackings: ReadonlySet<string> = new Set()): any | null {
    const now = Date.now();
    const eligible = notes
        .filter((n) => noteSpecks(n) >= needSpecks)
        .sort((a, b) => (noteSpecks(a) < noteSpecks(b) ? 1 : noteSpecks(a) > noteSpecks(b) ? -1 : 0));
    for (const n of eligible) {
        const key = backingKey(sessionId, n);
        if (skipBackings.has(key)) continue;
        const held = noteLocks.get(key);
        if (held && held.exp > now) continue;
        const token = ++noteLeaseSeq;
        noteLocks.set(key, { exp: now + ttlMs, token });
        return { note: n, key, token, backing: String(n?.token?.backingNight ?? '?').slice(0, 16) };
    }
    return null;
}

/** The note on the reserved backing that still covers the fee, or null. */
export function sufficientNoteOnBacking(sessionId: string, notes: any[], key: string, needSpecks: bigint): any | null {
    return notes.find((n) => backingKey(sessionId, n) === key && noteSpecks(n) >= needSpecks) ?? null;
}
/** Reserves a free backing, waiting up to `waitMs`. */
export async function acquireBacking(
    sessionId: string, refresh: () => Promise<any[]>, needSpecks: bigint, ttlMs: number, waitMs: number,
    skipBackings: ReadonlySet<string> = new Set()
): Promise<any> {
    const deadline = Date.now() + waitMs;
    for (; ;) {
        throwIfRpcCancelled('dust backing wait');
        const notes = await refresh();
        const leased = tryLockBacking(sessionId, notes, needSpecks, ttlMs, skipBackings);
        if (leased) return leased;
        if (Date.now() >= deadline) {
            throw new Error(`no free dust backing with >= ${needSpecks} specks within ${waitMs}ms (all backings busy)`);
        }
        await new Promise((r) => setTimeout(r, 1000));
    }
}
/** Does nothing when someone else took over the reservation. */
export function releaseNote(key: string, token: number): void {
    const held = noteLocks.get(key);
    if (held && held.token === token) noteLocks.delete(key);
}
/**
 * Renews a reservation while its job runs. The expiry only covers crashes,
 * so a running job must never lose its reservation. Returns a stop function.
 */
export function keepLeaseAlive(key: string, token: number, ttlMs: number): () => void {
    const every = Math.max(5, Math.floor(ttlMs / 3));
    const timer = setInterval(() => {
        const held = noteLocks.get(key);
        if (held && held.token === token) held.exp = Date.now() + ttlMs;
    }, every);
    timer.unref?.();
    return () => clearInterval(timer);
}
export function noteLeaseTtlMs(): number {
    return configMs('NIGHTGATE_NOTE_LEASE_MS');
}
export const __noteLeaseForTests = { tryLockBacking, sufficientNoteOnBacking, releaseNote, keepLeaseAlive, noteLeaseTtlMs, held: (key: string) => noteLocks.get(key), reset: () => noteLocks.clear() };

/** The sponsor adds the dust fee to a tx the caller finalized and sends it. */
export async function sponsorAndSubmitFinalized(sponsor: FacadeEntry, rehydrated: any, site: string, replyPort?: MessagePort, calls?: Array<{ address: string; entryPoint: string }>, minted: string[] = []): Promise<string> {
    await waitForGenuineSync(sponsor, BALANCE_SYNC_TIMEOUT_MS, `${site} sponsor`);
    await captureDustSnapshot(sponsor, `${site} sponsor`);
    const sponsorTtl = new Date(Date.now() + 30 * 60 * 1000);
    const sponsorRecipe = await sponsor.facade.balanceFinalizedTransaction(
        rehydrated,
        { shieldedSecretKeys: sponsor.zswapKeys, dustSecretKey: sponsor.dustKey },
        { ttl: sponsorTtl, tokenKindsToBalance: ['dust'] }
    );
    const finalized = await sponsor.facade.finalizeRecipe(sponsorRecipe);
    try {
        await announceSubmitIntent(replyPort, {
            txHash: String(finalized.identifiers().at(-1)),
            contractAddress: calls?.[0]?.address, circuits: calls?.map(c => c.entryPoint), sponsorAccountId: sponsor.sessionId,
            deployed: calls?.filter(c => c.entryPoint === DEPLOY_ENTRY_POINT).map(c => c.address) ?? [],
            ttl: sponsorTtl.toISOString(),
            segments: callSegments(finalized),
            ...(minted.length ? { minted } : {})
        });
    } catch (e) {
        await revertRecipeBestEffort(sponsor.facade, finalized, `${site} sponsor-intent`);
        throw e;
    }
    return String(await submitWithDustGuard(sponsor, finalized, `${site} sponsor-submit`));
}

/** Returns undefined without a sponsor id. Throws when the sponsor wallet is not loaded. */
export function resolveSponsorEntry(sponsorSessionId?: string): FacadeEntry | undefined {
    if (!sponsorSessionId) return undefined;
    const sponsor = facades.get(sponsorSessionId);
    if (!sponsor) {
        throw new Error(
            `No facade for sponsorSessionId=${sponsorSessionId.slice(0, 16)} ` +
            `(the sponsor session must be connected for signing and its facade initialised)`
        );
    }
    return sponsor;
}


/** Builds, signs and finalizes a call without paying the fee. Returns the tx as base64 and does not send it. */
export async function buildSponsorableTx(args: {
    sessionId: string; proxyId: string; contractName: string;
    registration: { artifactPath: string; artifactDigest?: string; privateStateId: string; zkConfigPath: string; slotWidth?: number };
    contractAddress: string; circuit: string; args?: unknown[];
    indexerHttpUrl: string; indexerWsUrl: string; proofServerUrl: string;
    networkId: string; merkleProof?: MerkleProofBundle; initialPrivateState?: unknown;
}) {
    const entry = facades.get(args.sessionId);
    if (!entry) throw new Error(`No facade for sessionId=${args.sessionId.slice(0, 16)}`);
    const sdk = await loadSdk();
    await ensureNetworkId(args.networkId, sdk);
    const compiledContract = await getOrCompileContract(args.contractName, args.registration, entry, args.merkleProof);
    const contractProviders = await buildWorkerContractProviders({
        indexerHttpUrl: args.indexerHttpUrl, indexerWsUrl: args.indexerWsUrl,
        proofServerUrl: args.proofServerUrl, zkConfigPath: artifactAssetPath(args.contractName, args.registration), generation: args.registration.artifactDigest
    });
    const privateStateProvider = createPrivateStateProxy(args.proxyId);
    const holder: { captured?: any } = {};
    const walletProvider = buildBuildOnlyWalletProvider(entry, holder);
    const providers = {
        ...contractProviders,
        publicDataProvider: withFindContractQueryCache(contractProviders.publicDataProvider, args.indexerHttpUrl),
        privateStateProvider, walletProvider, midnightProvider: walletProvider
    };
    const { contracts } = await loadContractsSdk();
    privateStateProvider.setContractAddress(args.contractAddress);
    const existing = await privateStateProvider.get(args.registration.privateStateId);
    const seed = existing === undefined || existing === null;
    const found = await contracts.findDeployedContract(providers, {
        contractAddress: args.contractAddress, compiledContract,
        privateStateId: args.registration.privateStateId,
        ...(seed ? { initialPrivateState: args.initialPrivateState ?? {} } : {})
    });
    const fn = found?.callTx?.[args.circuit];
    if (typeof fn !== 'function') throw new Error(`Circuit '${args.circuit}' not found on contract at ${args.contractAddress}`);
    try { await fn(...(args.args ?? [])); } catch (e) { if (!holder.captured) throw e; }
    const callerFinalized = holder.captured;
    if (!callerFinalized || typeof callerFinalized.serialize !== 'function') {
        throw new Error('phase 1 did not produce a serializable finalized transaction');
    }
    const bytes: Uint8Array = new Uint8Array(callerFinalized.serialize());
    log('info', `buildSponsorableTx: ${args.contractName}.${args.circuit} finalized (${bytes.length}B, fee-unpaid)`);
    return { finalizedTxB64: Buffer.from(bytes).toString('base64'), serializedBytes: bytes.length };
}

/** Checks a caller's finalized tx against the sponsor rules, pays its fee and sends it. */
export async function sponsorFinalizedTx(args: {
    sponsorSessionId: string; finalizedTxB64: string; networkId: string;
    allowedContracts?: string[]; allowedCircuits?: string[]; allowDeploy?: boolean; ownContracts?: string[]; allowedTokenTypes?: string[]; allowContractMints?: boolean;
    /** Set by the dispatcher. Used to announce the tx before sending it. */
    __replyPort?: MessagePort;
}) {
    const sponsor = resolveSponsorEntry(args.sponsorSessionId);
    if (!sponsor) throw new Error('sponsorFinalizedTx requires a sponsorSessionId');
    const sdk = await loadSdk();
    await ensureNetworkId(args.networkId, sdk);
    const { tx, bytes } = await deserializeFinalizedTx(args.finalizedTxB64);

    const calls = checkSponsorableShape(tx, bytes.length, args.allowedContracts, args.allowedCircuits, { allowDeploy: args.allowDeploy === true, ownContracts: args.ownContracts, allowedTokenTypes: args.allowedTokenTypes, nightTokenType: sdk.ledger.nativeToken().raw, allowContractMints: args.allowContractMints === true, deriveTokenType: tokenTypeDeriver(sdk.ledger) });
    log('info', `sponsorFinalizedTx: paying dust for ${calls.map(c => c.entryPoint).join('+')} (${bytes.length}B)`);
    const minted = mintedTypesOf(tx, args.allowContractMints, sdk.ledger);
    const txId = await sponsorAndSubmitFinalized(sponsor, tx, 'sponsor-endpoint', args.__replyPort, calls, minted);
    log('info', `sponsorFinalizedTx: LANDED txHash=${txId.slice(0, 16)}`);
    return {
        txHash: txId, circuits: calls.map(c => c.entryPoint), contractAddress: calls[0]?.address ?? '',
        deployed: calls.filter(c => c.entryPoint === DEPLOY_ENTRY_POINT).map(c => c.address),
        ...(minted.length ? { minted } : {})
    };
}

/** How often to pick another backing when the chosen one turns out to hold too little dust. */
export const MAX_BACKING_RESELECTS = 3;

export class DustBackingShortError extends Error {
    constructor(readonly backing: string, readonly held: bigint, readonly needed: bigint) {
        super(`dust backing ${backing} holds ${held} specks at the spend's block time, the fee needs ${needed}`);
        this.name = 'DustBackingShortError';
    }
}

/** The lowest unused segment id. The added dust spend needs a segment of its own. */
export function freeSegmentId(tx: any): number {
    const used = new Set<number>();
    const intents = tx?.intents;
    if (intents && typeof intents.keys === 'function') {
        for (const key of intents.keys()) used.add(Number(key));
    }
    for (let id = 1; id <= 65535; id++) {
        if (!used.has(id)) return id;
    }
    throw new SponsorRefusalError('refusing to sponsor: the transaction uses every segment id, none is left for the dust spend');
}

/** Builds the dust spend on the reserved backing. Runs under the wallet's session lock. */
async function buildDustSpend(
    sponsor: FacadeEntry, networkId: string, sdk: any, leased: any, needSpecks: bigint, ctime: Date, ttl: Date, segment: number
): Promise<{ dustUnproven: any }> {
    const CoreWalletApi = await loadDustCoreWallet();
    return withSessionLocks([sponsor.sessionId], async () => {
        if (facades.get(sponsor.sessionId) !== sponsor) {
            throw new Error('sponsor facade was evicted while waiting for the dust build lock');
        }
        const dws: any = await firstDustState(sponsor.facade.dust);
        const cab = dws.capabilities.coinsAndBalances;
        const fresh: any[] = Array.from(cab.getAvailableCoins(dws.state, ctime));
        const note = sufficientNoteOnBacking(sponsor.sessionId, fresh, leased.key, needSpecks);
        if (!note) {
            const onBacking = fresh.filter((n) => backingKey(sponsor.sessionId, n) === leased.key);
            const held = onBacking.reduce((m, n) => (noteSpecks(n) > m ? noteSpecks(n) : m), 0n);
            throw new DustBackingShortError(leased.backing, held, needSpecks);
        }
        const [spends] = CoreWalletApi.spendCoins(dws.state, sponsor.dustKey, [{ token: note.token, value: needSpecks }], ctime);
        const intent = sdk.ledger.Intent.new(ttl);
        intent.dustActions = new sdk.ledger.DustActions('signature', 'pre-proof', ctime, [spends[0]]);
        const dustUnproven = sdk.ledger.Transaction.fromParts(networkId).addIntent({ tag: 'specific', value: segment }, intent);
        return { dustUnproven };
    });
}

/**
 * Pays the fee for a caller tx that is not bound yet, using one reserved backing.
 * Many of these can run at once from one wallet. It does not change the wallet's own state,
 * so only the dust build takes the session lock.
 */
export async function sponsorUnboundTx(args: {
    sponsorSessionId: string; unboundTxB64?: string; networkId: string;
    /** The two halves of a shielded swap, used instead of one caller tx. */
    swap?: { makerHalfB64: string; takerHalfB64: string }; allowSwaps?: boolean;
    allowedContracts?: string[]; allowedCircuits?: string[]; allowDeploy?: boolean; ownContracts?: string[]; allowedTokenTypes?: string[]; allowContractMints?: boolean;
    /** Set by the dispatcher. Used to announce the tx before sending it. */
    __replyPort?: MessagePort;
}) {
    const sponsor = resolveSponsorEntry(args.sponsorSessionId);
    if (!sponsor) throw new Error('sponsorUnboundTx requires a sponsorSessionId');
    const sdk = await loadSdk();
    await ensureNetworkId(args.networkId, sdk);

    let callerTx: any;
    // A caller tx is unbound. A swap is bound when one of its halves arrived bound.
    let callerBound = false;
    let calls: Array<{ address: string; entryPoint: string }>;
    let swap: SwapTerms | undefined;
    let nullifiers: string[] = [];
    if (args.swap) {
        if (args.allowSwaps !== true) throw new SponsorRefusalError('refusing to sponsor: swaps are not sponsored for this caller');
        const maker = await deserializeSwapHalf(args.swap.makerHalfB64, 'maker half');
        const taker = await deserializeSwapHalf(args.swap.takerHalfB64, 'taker half');
        swap = checkSwapHalves(maker.tx, taker.tx, {
            allowedTokenTypes: args.allowedTokenTypes, nightTokenType: sdk.ledger.nativeToken().raw,
            maxInputs: configNumber('NIGHTGATE_SPONSOR_SWAP_MAX_INPUTS')
        });
        nullifiers = [...new Set([...swapHalfNullifiers(maker.tx), ...swapHalfNullifiers(taker.tx)])];
        const merged = mergeSwapHalves(maker, taker);
        callerTx = merged.tx;
        callerBound = merged.bound;
        assertSwapBalanced(callerTx, callerTx.serialize().length);
        calls = [{ address: '', entryPoint: SWAP_ENTRY_POINT }];
        log('info', `sponsorUnboundTx: swap of ${swap.gives.amount} ${swap.gives.tokenType.slice(0, 12)} for ${swap.wants.amount} ${swap.wants.tokenType.slice(0, 12)} (${callerBound ? 'bound' : 'unbound'} halves)`);
    } else {
        const deserialized = await deserializeFinalizedTx(String(args.unboundTxB64 ?? ''));
        callerTx = deserialized.tx;
        calls = checkSponsorableShape(callerTx, deserialized.bytes.length, args.allowedContracts, args.allowedCircuits, { allowDeploy: args.allowDeploy === true, ownContracts: args.ownContracts, allowedTokenTypes: args.allowedTokenTypes, nightTokenType: sdk.ledger.nativeToken().raw, allowContractMints: args.allowContractMints === true, deriveTokenType: tokenTypeDeriver(sdk.ledger) });
    }
    const minted = swap ? [] : mintedTypesOf(callerTx, args.allowContractMints, sdk.ledger);
    const contractAddress = calls[0]?.address || undefined;

    const dustSegment = freeSegmentId(callerTx);

    await waitForGenuineSync(sponsor, BALANCE_SYNC_TIMEOUT_MS, 'sponsor-unbound');

    const params = sdk.ledger.LedgerParameters.initialParameters();
    let needSpecks: bigint;
    try { needSpecks = callerTx.feesWithMargin(params, 2); }
    catch { needSpecks = 100_000_000n; } // fallback if the fee estimate fails
    if (needSpecks <= 0n) needSpecks = 100_000_000n;

    // Read `facade.dust` at each use and never cache it, because a dust restore replaces the object.
    const leaseTtlMs = noteLeaseTtlMs();
    const backingWaitMs = configMs('NIGHTGATE_BACKING_WAIT_MS');

    const tip = await getIndexerTip(sponsor.indexerHttpUrl);
    const ctime = (() => {
        const t = tip.timestampMs;
        if (t == null || !Number.isFinite(t)) return new Date();
        const ms = t > 1e12 ? t : t * 1000; // smaller values are seconds
        const d = new Date(ms);
        return Number.isNaN(d.getTime()) ? new Date() : d;
    })();
    const ttl = new Date(ctime.getTime() + 30 * 60 * 1000);

    const snapshotNotes = async (at: Date): Promise<any[]> => {
        const dws: any = await firstDustState(sponsor.facade.dust);
        const cab = dws.capabilities.coinsAndBalances;
        return Array.from(cab.getAvailableCoins(dws.state, at));
    };
    const shortBackings = new Set<string>();
    let leased: any;
    let built: { dustUnproven: any } | undefined;
    let stopRenewal: () => void = () => undefined;
    for (let attempt = 0; ; attempt++) {
        leased = await acquireBacking(sponsor.sessionId, () => snapshotNotes(ctime), needSpecks, leaseTtlMs, backingWaitMs, shortBackings);
        stopRenewal = keepLeaseAlive(leased.key, leased.token, leaseTtlMs);
        try {
            built = await buildDustSpend(sponsor, args.networkId, sdk, leased, needSpecks, ctime, ttl, dustSegment);
            break;
        } catch (e) {
            stopRenewal(); releaseNote(leased.key, leased.token);
            if (e instanceof DustBackingShortError && attempt < MAX_BACKING_RESELECTS) {
                log('warn', `sponsorUnboundTx: ${(e as Error).message}; selecting another backing`);
                shortBackings.add(leased.key);
                continue;
            }
            throw e;
        }
    }

    try {
        const tProve = Date.now();
        let provingService: any = sponsor.facade?.provingService;
        if (!provingService?.prove) {
            const provingSdk = await loadProvingSdk();
            const sharedKeys = await getSharedKeyMaterialProvider();
            provingService = provingSdk.makeWasmProvingService({ keyMaterialProvider: sharedKeys });
        }
        const dustProven = await provingService.prove(built!.dustUnproven);
        log('info', `sponsorUnboundTx: dust spend proven in ${Date.now() - tProve}ms (${sponsor.facade?.provingService?.prove ? resolveProvingMode() : 'wasm'})`);
        const bound = callerBound ? dustProven.bind().merge(callerTx) : dustProven.merge(callerTx).bind();
        await announceSubmitIntent(args.__replyPort, {
            txHash: String(bound.identifiers().at(-1)),
            contractAddress, circuits: calls.map(c => c.entryPoint), note: leased.backing, sponsorAccountId: sponsor.sessionId,
            deployed: calls.filter(c => c.entryPoint === DEPLOY_ENTRY_POINT).map(c => c.address),
            ttl: ttl.toISOString(),
            segments: callSegments(bound),
            ...(minted.length ? { minted } : {}),
            ...(nullifiers.length ? { nullifiers } : {})
        });
        const txId = await submitOnDedicatedClient(sponsor, bound, 'sponsor-unbound-submit');
        log('info', `sponsorUnboundTx: LANDED txHash=${String(txId).slice(0, 16)} on backing ${leased.backing}`);
        return {
            txHash: String(txId), circuits: calls.map(c => c.entryPoint), contractAddress: contractAddress ?? '', note: leased.backing,
            deployed: calls.filter(c => c.entryPoint === DEPLOY_ENTRY_POINT).map(c => c.address),
            ...(minted.length ? { minted } : {}),
            ...(swap ? { swap } : {}),
            ...(nullifiers.length ? { nullifiers } : {})
        };
    } finally {
        stopRenewal();
        releaseNote(leased.key, leased.token);
    }
}

export const sponsorHandlers = { buildSponsorableTx, sponsorFinalizedTx, sponsorUnboundTx, describeSwapHalf };
